--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleNPC
branches:
  - master
  - pm5
  - pm5-rus
projects:
  SimpleNPC:
    path: ""
    icon: "/assets/icon.png"
    libs:
      - src: dresnite/EasyUI/libEasyUI
        version: 1.0.3
...
