--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/SimpleNPC
build-by-default: true
branches:
  - pm5
projects:
  SimpleNPC:
    path: ""
    libs:
      - src: dresnite/EasyUI/libEasyUI
        version: 1.0.3
...
