name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 4.2.0-dev
api: 5.0.0
authors:
  - brokiem
  - supercrafter333 # I hope that's okay :)

website: https://github.com/brokiem/SimpleNPC

permissions:
  simplenpc.spawn:
    default: op
  simplenpc.edit:
    default: op
  simplenpc.id:
    default: op
  simplenpc.notify:
    default: op
  simplenpc.ui:
    default: op
  simplenpc.reload:
    default: op
  simplenpc.remove:
    default: op
  simplenpc.migrate:
    default: op
  simplenpc.list:
    default: op
  simplenpc.rca:
    default: op
